spring:
  profiles: test
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.xyz.test.com
profiles:
  active: test
base-url: "https://jsonmock.hackerrank.com/api/football_matches"

#The 3 dashes below separate individual profiles. So that we can contain multiple profiles (test, prod) in single yml file
---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com


